
default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: acclaim_dev

test:
  <<: *default
  database: acclaim_test

production:
  <<: *default
  database: acclaim_prod
